# Site settings
timezone: Europe/Berlin

baseurl: '' # the subpath of your site, e.g. /blog/
url: 'https://cginternals.github.io/webgl-operate' # the base hostname & protocol for your site

title: 'webgl-operate examples'
description: 'WebGL examples using webgl-operate, a TypeScript based WebGL rendering framework'
author: 'Daniel Limberger'

languages: [ 'en' ]

# Handling Reading
safe: true
encoding: utf-8

# Build settings
markdown: kramdown

# Outputting
exclude: [
  'Gemfile',
  'Gemfile.lock',
  'vendor',
  '.jekyll-metadata']

keep_files: [
  'doc',
  'test-results',
  'js/webgl-operate.js',
  'js/webgl-operate.slim.js',
  'js/webgl-operate.min.js',
  'js/webgl-operate.slim.min.js',
  'js/webgl-operate.js.map',
  'js/webgl-operate.slim.js.map' ]

# CSS Minification
sass:
  style: compressed
  