name: HiViSer

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  # Replace pull_request with pull_request_target if you
  # plan to use this action with forks, see the Limitations section
  pull_request:
    branches:
      - master

jobs:
  run-hiviser:
    name: Run HiViSer
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Run Hiviser Action
        uses: hpicgs/hiviser-action@v0
        # Optional, use if you want to analyze a specific folder
        with:
          repository_path: ./source
